### ISSUE TITLE
Does not respect namespace

### ISSUE THREAD

**Issue by pdilyard** [peburrows/diplomat#11]
I created a key with a namespace, and then used that key to create an entity, but the entity was insert into the `[default]` namespace in Datastore.

**Comment by peburrows** [comment]
Sorry, I've been gone on vacation for the last week and a half. I'll give this a look as soon as I catch up on my backlog from being out.

**Comment by pdilyard** [comment]
No worries, thank you

**Comment by peburrows** [comment]
@pdilyard, can you try the `namespaces` branch and see if that fixes your issue? Inserting should be as before, by creating a key with a namespace; querying will require passing the namespace as the second parameter, ala:

``` elixir
"select * from Message"
|> Query.new
|> Query.execute("my-namespace")
```
