### ISSUE TITLE
How mature is this library and is it production ready?

### ISSUE THREAD

**Issue by sashaafm** [peburrows/diplomat#2]
Hello, is Diplomat mature enough for daily use (or is production ready)? 

I'm building a Google Cloud APIs collection https://github.com/sashaafm/gcloudex. My next intention is to implement the Google Datastore API. Can this library be used for that purpose as dependency? 

Also if you're interested in contributing to the project you're welcome :)

**Comment by peburrows** [comment]
Yeah, Diplomat is fairly mature — we're about to be using it in production. Google deprecated the v2 protocol buffer API out from under me, but it still works, and I'm working on switching over to the v3 API.

Long story short: yes, Diplomat should be a good choice for the Datastore dependency for your lib.

**Comment by kiennt** [comment]
Nice, I am glad we have this discussion.

@peburrows would you mind to tell me about your status of switching to v3 API? And what I could do to help you because I also want to do that in my product :)

**Comment by peburrows** [comment]
@kiennt, the two main issues are that extprotobuf doesn't currently support everything in the v1beta3 protocol buffer definitions and the need for an http/2 client to use grpc.

**Comment by peburrows** [comment]
Diplomat is now on v1beta3 and in use in a couple different production environments that I know about, so I'm gonna go ahead and close this issue.
