### ISSUE TITLE
module :unicode_util is not available

### ISSUE THREAD

**Issue by antonibertel** [peburrows/diplomat#23]
Hi,

My system dependencies are:
Erlang/OTP 19 [erts-8.3] [64-bit] [smp:4:4] [async-threads:10]
Elixir 1.4.4

Part of my project dependencies:
diplomat ~> 0.7
goth ~> 0.4

I unsuccessfully tried to update 'hackney' dependency. 

## Stacktrace
```
 ** (UndefinedFunctionError) function :unicode_util.lowercase/1 is undefined (module :unicode_util is not available)
        :unicode_util.lowercase('www.googleapis.com')
        (idna) c:/projects/SpeechRecognitionServer/deps/idna/src/idna.erl:57: :idna.lowercase_list/1
        (idna) c:/projects/SpeechRecognitionServer/deps/idna/src/idna.erl:10: :idna.to_ascii/1
        (hackney) c:/projects/SpeechRecognitionServer/deps/hackney/src/hackney_url.erl:96: :hackney_url.normalize/2
        (hackney) c:/projects/SpeechRecognitionServer/deps/hackney/src/hackney.erl:291: :hackney.request/5
        (httpoison) lib/httpoison/base.ex:432: HTTPoison.Base.request/9
        (goth) lib/goth/client.ex:53: Goth.Client.get_access_token/2
        (goth) lib/goth/token.ex:94: Goth.Token.retrieve_and_store!/1
        lib/diplomat/client.ex:138: Diplomat.Client.auth_header/0
        lib/diplomat/client.ex:109: Diplomat.Client.call/2
        lib/diplomat/client.ex:43: Diplomat.Client.commit/1
        lib/diplomat/entity.ex:138: Diplomat.Entity.insert/1
        (web) web/controllers/page_controller.ex:12: Web.PageController.myTest/2

**Comment by peburrows** [comment]
Hrm, this looks like an issue in hackney (or one of its dependencies), and may only occur on Windows. There's a recent discussion on Elixir Forum about this issue, but the thread doesn't currently have any resolution: https://elixirforum.com/t/programming-elixir-chapter-13-problem/5793

**Comment by antonibertel** [comment]
Hi @peburrows,

Many thanks for the quick reply.
I create another one issue for hackney: https://github.com/benoitc/hackney/issues/413
I also tried to manually apply different versions of dependencies as well as use 'unicode_util_compat' library - no luck.

**Comment by antonibertel** [comment]
The same error was on Ubuntu 14.04 (the same sources), but when i recompile project, error is gone.
The compiled project on Ubuntu works fine on Windows. 

Windows setup:
Erlang/OTP 19 [erts-8.3] [64-bit] [smp:4:4] [async-threads:10]
Elixir 1.4.4
Ubuntu setup:
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]
Elixir 1.4.4
