### ISSUE TITLE
Is there a function for deleting an entity? 

### ISSUE THREAD

**Issue by mitcheaton1** [peburrows/diplomat#28]
I'm guessing that I'm totally missing something.

**Comment by peburrows** [comment]
Currently, you can only delete within the context of a transaction ([docs here](https://hexdocs.pm/diplomat/Diplomat.Transaction.html#delete/2)):

```elixir
Transaction.begin fn t ->
  # deletes are all done via a %Key{}
  Transaction.delete(t, key)
end
```

Now that I type that out, it feels like a strange limitation, and I'm not sure why I haven't implemented the ability to delete outside the context of a transaction 🤔 I'll add that to my todo list, but for now, using a `Transaction` is the answer.

**Comment by mitcheaton1** [comment]
Thanks!
