### ISSUE TITLE
:undefined error after hot code update,

### ISSUE THREAD

**Issue by noizu** [peburrows/diplomat#36]
After deploying a hot update with distillery connection begins to fail with an :undefined response. 
Hot update using distillery version 1.5.2

 GoldenRatio.Appengine.UserEntity.entity!("r6EhunDmTsbYuJqEcN7bNq0Yedg2")
** (MatchError) no match of right hand side value: :undefined
    (hackney) /mnt/data/code/lax-alerts/src/ingressor/src/deps/hackney/src/hackney_connect.erl:69: :hackney_connect.
create_connection/5
    (hackney) /mnt/data/code/lax-alerts/src/ingressor/src/deps/hackney/src/hackney_connect.erl:37: :hackney_connect.
connect/5
    (hackney) /mnt/data/code/lax-alerts/src/ingressor/src/deps/hackney/src/hackney.erl:315: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:439: HTTPoison.Base.request/9
    (goth) lib/goth/client.ex:49: Goth.Client.get_access_token/2
    (goth) lib/goth/token.ex:94: Goth.Token.retrieve_and_store!/1
    (diplomat) lib/diplomat/client.ex:141: Diplomat.Client.auth_header/0
    (diplomat) lib/diplomat/client.ex:109: Diplomat.Client.call/2

**Comment by peburrows** [comment]
By the stacktrace, it appears this might be an issue with hackney, not Diplomat or Goth directly, but I'll have to dig in and see if that is indeed the case. If you have a simple code sample where you can reliably reproduce, that would be helpful. Thanks!

**Comment by noizu** [comment]
Thanks for the follow up. Looks like the underlying issue was fixed in Hackney 1.1.13. 
https://github.com/benoitc/hackney/issues/492.

changing my deps entry to `{:hackney, "1.13.0", override: true }` resolved the issue for me.
