### ISSUE TITLE
Parse binary errors

### ISSUE THREAD

**Issue by pdilyard** [peburrows/diplomat#8]
Errors come back from the API and are not parsed in any way, so all the Diplomat user gets is something like this:

``` elixir
{:error,
 <<8, 3, 18, 52, 99, 97, 110, 110, 111, 116, 32, 119, 114, 105, 116, 101, 32,
   109, 111, 114, 101, 32, 116, 104, 97, 110, 32, 53, 48, 48, 32, 101, 110, 116,
   105, 116, 105, 101, 115, 32, 105, 110, 32, 97, 32, 115, 105, 110, 103, ...>>}
```

Would be very nice if this was something more useful 😄

**Comment by peburrows** [comment]
Yeah, that error is pretty useless 😞. 

Do you have simple steps to reproduce an error like this?

**Comment by pdilyard** [comment]
The simplest way:

``` elixir
Diplomat.Entity.new(%{"a" => 1}) |> Diplomat.Entity.insert() # exclude an entity type
```

I think you can also produce an error like this by passing an invalid GQL query, which probably would be the most useful time to get back a meaningful error.

**Comment by peburrows** [comment]
Awesome, thanks! I'll dig into this soon.

**Comment by peburrows** [comment]
@pdilyard I've just pushed v0.2.2 to hex with a fix for this. 

(I wasn't thinking or I would have just rolled it into v0.2.1 with the namespace fix, but whatever).
