### ISSUE TITLE
Support for namespacing?

### ISSUE THREAD

**Issue by pdilyard** [peburrows/diplomat#9]
Is there support for configuring namespaces? It would be nice to easily specify different namespaces for dev/stage/prod.

https://cloud.google.com/datastore/docs/concepts/multitenancy

**Comment by peburrows** [comment]
There's support for namespaces if you craft the Entity key manually (see: https://github.com/peburrows/diplomat/blob/master/lib/diplomat/key.ex#L39-L42), but there's no convenient way to configure namespaces at a global level (or to specify a namespace for an entity's key w/o building the key manually yourself).

I'll look into potentially exposing a more convenient way of handling key namespaces.

**Comment by pdilyard** [comment]
How do you actually use the key to insert an entity? I don't see any functions that allow you to pass the key as a parameter, except the query functions.

**Comment by peburrows** [comment]
Oh man, you're absolutely right. I thought for sure I had exposed a function to create an Entity with a Key, but I was wrong. I'll add that now.

**Comment by pdilyard** [comment]
Thanks! We're about to start using this library to refactor some of our data storage, so I appreciate the responsiveness! 😄

**Comment by peburrows** [comment]
@pdilyard I just published v0.2.1 to hex with a fix for this. Let me know if that allows you to do what you are wanting.

Longer term, I think it makes sense to allow you to configure a default namespace at the project level, so I'll add that to my todo list.

**Comment by pdilyard** [comment]
Agreed. For now, I'll just write a simple wrapper or utility function.
